language: ruby
rvm:
- 2.1.2
branches:
  only:
  - master
before_script:
  - gem install asciidoctor
  - gem install pygments.rb
script: ./deploy.sh

# GitHub Token configuration for deploying the Ion Doc static site to ionwg.github.io
#
# If you want to be able to deploy the site to ionwg.github.io:
#
# 1. Ensure you have the travis gem installed:
#
#     gem install travis
#
# 2. Create a GitHub authentication token for the ionwg/ionwg.github.io repository as described here:
#
#    https://help.github.com/articles/creating-an-access-token-for-command-line-use/
#
# 3. Change the 'secure' value below to be the output of the following command:
#
#     travis encrypt 'GIT_EMAIL=YOUR_EMAIL GH_TOKEN=YOUR_GH_TOKEN'
#
# where YOUR_EMAIL is your actual email address and YOUR_GH_TOKEN is your actual GitHub token value created in #2.
env:
  global:
    - GITHUB_REPO='git@github.com:ionwg/ionwg.github.io.git'
    - secure: "eQTLtbtOXBkK58L5pFDuJMthghuMZ1i26wJ10wShZoXU+UjoDsa07K9bUbRSssxzGBx6+KcqVcb857immsm3/i3h97fKndIuRVW+6VX9lsWqZWaRI7kQMcQBQd9ymDkUsO4S/mwRROmtICf77gcuLiZlh1IA8ZixKc+fC3twhuQ="